---
- name: Create new user devuser
  user:
    name: devuser
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: Create .ssh directory for devuser
  file:
    path: /home/devuser/.ssh
    state: directory
    owner: devuser
    group: devuser
    mode: '0700'

- name: Add SSH key for devuser
  authorized_key:
    user: devuser
    state: present
    key: "{{ lookup('file', '~/.ssh/Ansible-key.pem.pub') }}"

- name: Deploy hardened sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart SSH
